version: "3.8"
services:
  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: arros
      MINIO_ROOT_PASSWORD: eros1004
    ports:
      - 9000:9000
      - 9001:9001
  minio_init:
    image: minio/mc
    restart: on-failure
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -ce "
      /usr/bin/mc config host add minio http://minio:9000 arros eros1004;
      /usr/bin/mc mb --ignore-existing minio/arros;
      /usr/bin/mc mb --ignore-existing minio/contents;
      /usr/bin/mc admin config set minio notify_kafka:arros brokers=redpanda:9092 topic=contents;
      /usr/bin/mc admin service restart minio;
      /usr/bin/mc event add --event put minio/contents arn:minio:sqs::arros:kafka;
      exit 0;
      "

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: arros
      POSTGRES_PASSWORD: eros1004
    ports:
      - 5432:5432

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    healthcheck:
      test:
        ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  redpanda_console:
    image: docker.redpanda.com/redpandadata/console:latest
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - 8080:8080
    depends_on:
      - redpanda

  arros:
    image: ingkle/arross
    pull_policy: always
    container_name: arros
    restart: always
    command:
      - --logfilter
      - arros=debug
      - --metastore
      - postgres://arros:eros1004@postgres:5432/postgres
      - --functions
      - /opt/scripts/functions.yaml
    ports:
      - 8888:8888
    environment:
      AWS_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: arros
      AWS_SECRET_ACCESS_KEY: eros1004
      AWS_REGION: default
      AWS_S3_ALLOW_UNSAFE_RENAME: true
      AWS_ALLOW_HTTP: true
      AWS_FORCE_PATH_STYLE: true
    depends_on:
      - postgres

  pyruntime:
    image: ingkle/arross-pyruntime
    pull_policy: always
    container_name: pyruntime
    restart: always
    command:
      - --server
      - http://arros:8888
      - --endpoint
      - http://pyruntime:8088
      - --port
      - "8088"
    ports:
      - 8088:8088
    environment:
      AWS_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: arros
      AWS_SECRET_ACCESS_KEY: eros1004
      AWS_REGION: default
      AWS_S3_ALLOW_UNSAFE_RENAME: true
      AWS_ALLOW_HTTP: true
      AWS_FORCE_PATH_STYLE: true
