DROP TABLE IF EXISTS contents;
DROP TABLE IF EXISTS buffer0;
CREATE UNBOUNDED EXTERNAL TABLE contents STORED AS KAFKA LOCATION 'contents' OPTIONS ('bootstrap.servers' 'redpanda:9092', 'security.protocol' 'plaintext');
LOAD 'model=resnet50:latest';
SET model='resnet50';
SET provider='CPUExecutionProvider';
CREATE FUNCTION s3event(varchar, varchar) RETURNS varchar AS 's3event';
CREATE FUNCTION s3presign(varchar) RETURNS varchar AS 's3presign';
CREATE FUNCTION onnx(varchar) RETURNS bigint AS 'onnx';
CREATE UNBOUNDED EXTERNAL TABLE buffer0 (url varchar, result bigint) STORED AS BUFFER location 'buffer0';
CREATE VIEW events AS SELECT s3event(__meta__payload, 'create') AS object FROM contents;
INSERT INTO buffer0 SELECT object, onnx(s3presign(object)) FROM events;